var NumberOfWords = 113
var words = new BuildArray(NumberOfWords)

// Use the following variables to 
// define your random words:
words[1] = "https://enrt.eu/C1tLg"
words[2] = "https://enrt.eu/C1tLg"
words[3] = "https://enrt.eu/PYuLpE5"
words[4] = "https://enrt.eu/rfCEpnG4"
words[5] = "https://enrt.eu/yOOhp"
words[6] = "https://enrt.eu/BWmKh7"
words[8] = "https://enrt.eu/qjpr"
words[9] = "https://enrt.eu/AR6LanHR"
words[10] = "https://enrt.eu/GTBsT7"
words[11] = "https://enrt.eu/ZSF1O3ZO"
words[12] = "https://enrt.eu/rBHK"
words[13] = "https://enrt.eu/id146wy"
words[14] = "https://enrt.eu/RTnWR"
words[15] = "https://enrt.eu/bGEO"
words[16] = "https://enrt.eu/EPcTnxj"
words[17] = "https://enrt.eu/9O8X"
words[18] = "https://enrt.eu/NTQ3X"
words[19] = "https://enrt.eu/w76k"
words[20] = "https://enrt.eu/9FvL7g"
words[21] = "https://enrt.eu/WTuDieQo"
words[22] = "https://enrt.eu/rzYd"
words[23] = "https://enrt.eu/yDst"
words[24] = "https://enrt.eu/HwK99"
words[25] = "https://enrt.eu/xRiYFbK"
words[26] = "https://enrt.eu/kogU"
words[27] = "https://enrt.eu/1EeJOQ"
words[28] = "https://enrt.eu/RCCJIf"
words[29] = "https://enrt.eu/YViFAXUo"
words[30] = "https://enrt.eu/AtEBA"
words[31] = "https://enrt.eu/M5FXU"
words[32] = "https://enrt.eu/1Bhw"
words[33] = "https://enrt.eu/MWqvN"
words[34] = "https://enrt.eu/WlS2RV9"
words[35] = "https://enrt.eu/qTRMTjvM"
words[36] = "https://enrt.eu/Ndql"
words[37] = "https://enrt.eu/Yjat"
words[38] = "https://enrt.eu/3HxUu5W"
words[39] = "https://enrt.eu/l2R362Ag"
words[40] = "https://enrt.eu/l2R362Ag"
words[41] = "https://enrt.eu/Xdgc7I"
words[42] = "https://enrt.eu/46ke"
words[43] = "https://enrt.eu/fr4fZ"
words[44] = "https://enrt.eu/gH6I"
words[45] = "https://enrt.eu/dNsmyWTW"
words[46] = "https://enrt.eu/7O6M8"
words[47] = "https://enrt.eu/4m0N"
words[48] = "https://enrt.eu/7OczN8T"
words[49] = "https://enrt.eu/nnav6"
words[50] = "https://enrt.eu/cF74W"
words[51] = "https://enrt.eu/cF74W"
words[52] = "https://enrt.eu/nvMJ43g"
words[53] = "https://enrt.eu/SnIY2Fw"
words[54] = "https://enrt.eu/vZOdf"
words[55] = "https://enrt.eu/Nmyf"
words[56] = "https://enrt.eu/eS554pkk"
words[57] = "https://enrt.eu/MNpc0C"
words[58] = "https://enrt.eu/V648D0C"
words[59] = "https://enrt.eu/UOGPW"
words[60] = "https://enrt.eu/kQXFe"
words[61] = "https://enrt.eu/oXg9N"
words[62] = "https://enrt.eu/bfLNz1"
words[63] = "https://enrt.eu/Au3EH"
words[64] = "https://enrt.eu/R89vI2"
words[65] = "https://enrt.eu/LfI4gN8I"
words[66] = "https://enrt.eu/p133wo"
words[67] = "https://enrt.eu/pchzx"
words[68] = "https://enrt.eu/wjoGDL"
words[69] = "https://enrt.eu/xQ1SCYby"
words[70] = "https://enrt.eu/IbiwvXsu"
words[71] = "https://enrt.eu/Bf7Eo"
words[72] = "https://enrt.eu/gF7fL"
words[73] = "https://enrt.eu/dzkkxpj"
words[74] = "https://enrt.eu/0PJ6ig"
words[75] = "https://enrt.eu/Llq5x43"
words[76] = "https://enrt.eu/k39oEOL9"
words[77] = "https://enrt.eu/hu6vXdtr"
words[78] = "https://enrt.eu/0cmFaK"
words[79] = "https://enrt.eu/0KPIE2"
words[80] = "https://enrt.eu/JJQ9GGmp"
words[81] = "https://enrt.eu/K9s8"
words[82] = "https://enrt.eu/nAUjpy"
words[83] = "https://enrt.eu/ZIKF"
words[84] = "https://enrt.eu/pUNBbe7"
words[85] = "https://enrt.eu/vtdfiz"
words[86] = "https://enrt.eu/6IoMqit7"
words[87] = "https://enrt.eu/OxCGhG"
words[88] = "https://enrt.eu/syCnr"
words[89] = "https://enrt.eu/lgzXx4t"
words[90] = "https://enrt.eu/IzWHT1Y"
words[91] = "https://enrt.eu/obTVEI"
words[92] = "https://enrt.eu/nvOjFhe"
words[93] = "https://enrt.eu/3BQxMa"
words[94] = "https://enrt.eu/0YIo"
words[95] = "https://enrt.eu/CHSUBA4"
words[96] = "https://enrt.eu/OxlQB8Bb"
words[97] = "https://enrt.eu/WPyrV"
words[98] = "https://enrt.eu/o9SpF7"
words[99] = "https://enrt.eu/l87qP0"
words[100] = "https://enrt.eu/taDy1"
words[101] = "https://enrt.eu/OGJsRw"
words[102] = "https://enrt.eu/8U5bA"
words[103] = "https://enrt.eu/2QK45"
words[104] = "https://enrt.eu/ED6IfFQ1"
words[105] = "https://enrt.eu/R1NlF"
words[106] = "https://enrt.eu/gaj9WeVa"
words[107] = "https://enrt.eu/PDqDyvpc"
words[108] = "https://enrt.eu/gVexLir"
words[109] = "https://enrt.eu/ibXmnS"
words[110] = "https://enrt.eu/ew9q"
words[111] = "https://enrt.eu/8HUcSD"
words[102] = "https://enrt.eu/pjdajUf"
words[103] = "https://enrt.eu/jGPJemOP"
words[104] = "https://enrt.eu/tMRGu5k"
words[105] = "https://enrt.eu/Ypwai"
words[106] = "https://enrt.eu/CwWbn"
words[107] = "https://enrt.eu/nIbjNXV"
words[108] = "https://enrt.eu/mWYRKW"
words[109] = "https://enrt.eu/3h8adsAW"
words[110] = "https://enrt.eu/C2t3"
words[111] = "https://enrt.eu/w65oxC"
words[112] = "https://enrt.eu/P1rA8Q"
words[113] = "https://enrt.eu/94zb"


function BuildArray(size){
this.length = size
for (var i = 1; i <= size; i++){
this[i] = null}
return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
frm.WordBox.value = words[rnd]
}